### ISSUE TITLE
incompatible with PHP 7.4

### ISSUE THREAD

**Issue by da-anda** [RevertIT/mybb-rt_disposablemails#1]
Hi,

the current version of DisposableMails is unfortunately incompatible with PHP 7.4 due to the return value declaration of `: mixed` here https://github.com/RevertIT/mybb-rt_disposablemails/blob/main/inc/plugins/rt_disposablemails.php#L428

it should be `: array`, as this method clearly will always return an array

**Comment by RevertIT** [comment]
That's correct. I've been developing 4 plugins at the same time, so it was overlooked on my end, thank you.

**Comment by da-anda** [comment]
thanks for the fast fix
